### PR TITLE
ENH: Checks truth value of notify filter label

### PR DESCRIPTION
**Pull request by thomasjpfan**
Addresses https://github.com/docker-flow/docker-flow-swarm-listener/issues/38

### CODE REVIEW

**Comment by thomasjpfan** [comment]
@vfarcic There seems to be an issue with the Jenkins CI.

**Comment by vfarcic** [comment]
Skiing whole week without laptop. I will not be able to check it before the weekend.

**Comment by thomasjpfan** [comment]
Okay! Hope you are having fun! 😊

**Comment by vfarcic** [comment]
Fixed :)

**Pull request merged**
